-------------------------------------------------------------------------------
--  EllesmereUIBasics.lua  (shim for v6.6)
-- Gly
--  Basics has been split into per-module addons: EllesmereUIMinimap,
--  EllesmereUIFriends, EllesmereUIQuestTracker, EllesmereUIQoL (cursor),
--  EllesmereUIChat, EllesmereUIDamageMeters, EllesmereUIBlizzardSkin.
--
--  This shim exists purely so users who have Basics disabled can be detected
--  by the v66_basics_split_disabled_state migration in EllesmereUI_Migration.lua,
--  which mirrors that state onto the new addons. Once that migration has run
--  for all active characters, this addon can be removed outright.
-------------------------------------------------------------------------------
